apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-craneimage-admin-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - image.autocrane.io
  resources:
  - craneimages
  verbs:
  - '*'
- apiGroups:
  - image.autocrane.io
  resources:
  - craneimages/status
  verbs:
  - get
