apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-craneimagepolicy-admin-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - image.autocrane.io
  resources:
  - craneimagepolicies
  verbs:
  - '*'
- apiGroups:
  - image.autocrane.io
  resources:
  - craneimagepolicies/status
  verbs:
  - get
