apiVersion: image.autocrane.io/v1beta1
kind: CraneImage
metadata:
  labels:
    app.kubernetes.io/name: autocrane-operator
    app.kubernetes.io/managed-by: kustomize
  name: craneimage-sample
spec:
  source:
    registry: local-registry.default.svc.cluster.local:5000
  destination:
    registry: docker.io
    credentialsSecret: dockerhub-secret
  image:
    name: jordanbmoore/test-autocrane
    tag: upload-test