apiVersion: image.autocrane.io/v1beta1
kind: CraneImagePolicy
metadata:
  labels:
    app.kubernetes.io/name: autocrane-operator
    app.kubernetes.io/managed-by: kustomize
  name: craneimagepolicy-sample
spec:
  destination:
    registry: local-registry.default.svc.cluster.local:5000
  source:
    registry: docker.io
    credentialsSecret: dockerhub
  imagePolicy:
    name: 
      exact: "ubuntu"
    tag: 
      regex: "^\d\d\.\d\d$"