kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: autocrane
nodes:
  - role: control-plane
    extraPortMappings:
      # Expose the local registry on localhost:5000
      - containerPort: 5000
        hostPort: 5000
        protocol: TCP
  - role: worker
  - role: worker