# This rule is not used by the project autocrane-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the image.autocrane.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: autocrane-operator
    app.kubernetes.io/managed-by: kustomize
  name: craneimagepolicy-editor-role
rules:
- apiGroups:
  - image.autocrane.io
  resources:
  - craneimagepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image.autocrane.io
  resources:
  - craneimagepolicies/status
  verbs:
  - get
