---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - image.autocrane.io
  resources:
  - craneimagepolicies
  - craneimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image.autocrane.io
  resources:
  - craneimagepolicies/finalizers
  - craneimages/finalizers
  verbs:
  - update
- apiGroups:
  - image.autocrane.io
  resources:
  - craneimagepolicies/status
  - craneimages/status
  verbs:
  - get
  - patch
  - update
